package com.mc.codegen;

import junit.framework.TestCase;

import com.mc.utils.codegen.CodeGenFactory;
import com.mc.utils.codegen.structure.AnnotationMetaData;
import com.mc.utils.codegen.structure.AnnotationParameter;
import com.mc.utils.codegen.structure.ClassMetaData;
import com.mc.utils.codegen.structure.MemberMetaData;
import com.sun.codemodel.JCodeModel;

public class FixedFormatRecordGenTest extends TestCase {

    private static final String PACKAGE_NAME = "com.mc.domainobjects";

    private static final String OUTPUT_DIRECTORY = "output";

    public static void main(String[] args) throws Exception {
        String className = "Person";
        ClassMetaData classMetaData = new ClassMetaData();
        classMetaData.setPackageName(PACKAGE_NAME);
        classMetaData.setClassName(className);
        classMetaData.setJavaDocs("This class is generated by Vinod.");

        AnnotationMetaData annotationMetaData = new AnnotationMetaData();
        annotationMetaData.setMainAnnotationClass("com.ancientprogramming.fixedformat4j.annotation.Record");
        classMetaData.addAnnotationMetaData(annotationMetaData);

        MemberMetaData memberMetaData = new MemberMetaData();
        memberMetaData.setMemberName("stringData");
        memberMetaData.setDataType("String");
        memberMetaData.setJavaDocs("String data");
        memberMetaData.setRequireGetterSetterMethods(true);

        AnnotationMetaData fieldsAnnotationMetaData = new AnnotationMetaData();
        fieldsAnnotationMetaData.setMainAnnotationClass("com.ancientprogramming.fixedformat4j.annotation.Fields");
        
        AnnotationMetaData fieldAnnotationMetaData = new AnnotationMetaData();
        fieldAnnotationMetaData.setMainAnnotationClass("com.ancientprogramming.fixedformat4j.annotation.Field");
        fieldAnnotationMetaData.addAnnotationParameter(new AnnotationParameter("offset", "int", "1"));
        fieldAnnotationMetaData.addAnnotationParameter(new AnnotationParameter("length", "int", "1"));
        fieldAnnotationMetaData.addAnnotationParameter(new AnnotationParameter("align",
                "com.ancientprogramming.fixedformat4j.annotation.Align.RIGHT", true));
        fieldAnnotationMetaData.addAnnotationParameter(new AnnotationParameter("paddingChar", "char", "0x"));

        fieldsAnnotationMetaData.addAnnotationMetaData(fieldAnnotationMetaData);
        memberMetaData.addGetterAnnotationMetaData(fieldsAnnotationMetaData);

        classMetaData.addMemberMetaData(memberMetaData);

        MemberMetaData memberMetaData1 = new MemberMetaData();
        memberMetaData1.setMemberName("dob");
        memberMetaData1.setDataType("java.util.Date");
        memberMetaData1.setJavaDocs("Date of Birth");
        memberMetaData1.setRequireGetterSetterMethods(true);

        classMetaData.addMemberMetaData(memberMetaData1);

        JCodeModel codeModel = CodeGenFactory.createClass(classMetaData);

        CodeGenFactory.writeCodeModel(codeModel, OUTPUT_DIRECTORY);
    }

}
