
package com.mc.inputfile.amex.records;

import java.util.Date;
import com.ancientprogramming.fixedformat4j.annotation.Align.RIGHT;
import com.ancientprogramming.fixedformat4j.annotation.Field;
import com.ancientprogramming.fixedformat4j.annotation.Fields;
import com.ancientprogramming.fixedformat4j.annotation.Record;


/**
 * This class is +generated by Vinod.
 * 
 */
@Record
public class MyPerson {

    /**
     * MyPerson Header
     * 
     */
    private String Header;
    /**
     * MyPerson first name
     * 
     */
    private String firstname;
    /**
     * MyPerson last name
     * 
     */
    private String lastname;
    /**
     * MyPerson age
     * 
     */
    private String age;
    /**
     * MyPerson joiningDate
     * 
     */
    private Date joiningDate;
    /**
     * MyPerson salary
     * 
     */
    private Double salary;
    /**
     * MyPerson Filler
     * 
     */
    private String Filler;
    /**
     * MyPerson Footer
     * 
     */
    private String Footer;

    /**
     * Sets Header field value.
     * 
     * @param Header
     *                 The Header to set.
     */
    public final String setHeader(String Header) {
        this.Header = Header;
    }

    /**
     * This method returns the Header value.<BR>
     * 
     * @return
     *     Returns the Header.
     */
    @Fields({
        @Field(offset = 1, length = 5, paddingChar = '\'')
    })
    public final String getHeader() {
        return this.Header;
    }

    /**
     * Sets firstname field value.
     * 
     * @param firstname
     *                 The firstname to set.
     */
    public final String setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method returns the firstname value.<BR>
     * 
     * @return
     *     Returns the firstname.
     */
    @Fields({
        @Field(offset = 6, length = 10, paddingChar = '\'')
    })
    public final String getFirstname() {
        return this.firstname;
    }

    /**
     * Sets lastname field value.
     * 
     * @param lastname
     *                 The lastname to set.
     */
    public final String setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method returns the lastname value.<BR>
     * 
     * @return
     *     Returns the lastname.
     */
    @Fields({
        @Field(offset = 16, length = 10, paddingChar = '\'')
    })
    public final String getLastname() {
        return this.lastname;
    }

    /**
     * Sets age field value.
     * 
     * @param age
     *                 The age to set.
     */
    public final String setAge(String age) {
        this.age = age;
    }

    /**
     * This method returns the age value.<BR>
     * 
     * @return
     *     Returns the age.
     */
    @Fields({
        @Field(offset = 26, length = 2, paddingChar = ' ')
    })
    public final String getAge() {
        return this.age;
    }

    /**
     * Sets joiningDate field value.
     * 
     * @param joiningDate
     *                 The joiningDate to set.
     */
    public final Date setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    /**
     * This method returns the joiningDate value.<BR>
     * 
     * @return
     *     Returns the joiningDate.
     */
    @Fields({
        @Field(offset = 28, length = 8, paddingChar = ' ')
    })
    public final Date getJoiningDate() {
        return this.joiningDate;
    }

    /**
     * Sets salary field value.
     * 
     * @param salary
     *                 The salary to set.
     */
    public final Double setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method returns the salary value.<BR>
     * 
     * @return
     *     Returns the salary.
     */
    @Fields({
        @Field(offset = 36, length = 8, align = RIGHT.class, paddingChar = ' ')
    })
    public final Double getSalary() {
        return this.salary;
    }

    /**
     * Sets Filler field value.
     * 
     * @param Filler
     *                 The Filler to set.
     */
    public final String setFiller(String Filler) {
        this.Filler = Filler;
    }

    /**
     * This method returns the Filler value.<BR>
     * 
     * @return
     *     Returns the Filler.
     */
    @Fields({
        @Field(offset = 44, length = 22, paddingChar = '\'')
    })
    public final String getFiller() {
        return this.Filler;
    }

    /**
     * Sets Footer field value.
     * 
     * @param Footer
     *                 The Footer to set.
     */
    public final String setFooter(String Footer) {
        this.Footer = Footer;
    }

    /**
     * This method returns the Footer value.<BR>
     * 
     * @return
     *     Returns the Footer.
     */
    @Fields({
        @Field(offset = 66, length = 5, paddingChar = '\'')
    })
    public final String getFooter() {
        return this.Footer;
    }

}
