
package com.mc.inputfile.amex.records;

import java.util.Date;
import com.ancientprogramming.fixedformat4j.annotation.Align;
import com.ancientprogramming.fixedformat4j.annotation.Field;
import com.ancientprogramming.fixedformat4j.annotation.Fields;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatDecimal;
import com.ancientprogramming.fixedformat4j.annotation.FixedFormatPattern;
import com.ancientprogramming.fixedformat4j.annotation.Record;


/**
 * This class is generated by Vinod.
 * 
 */
@Record
public class MyPerson {

    /**
     * MyPerson Header
     * 
     */
    private String header;
    /**
     * MyPerson first name
     * 
     */
    private String firstname;
    /**
     * MyPerson last name
     * 
     */
    private String lastname;
    /**
     * MyPerson age
     * 
     */
    private int age;
    /**
     * MyPerson joiningDate
     * 
     */
    private Date joiningDate;
    /**
     * MyPerson salary
     * 
     */
    private Double salary;
    /**
     * MyPerson Filler
     * 
     */
    private String filler;
    /**
     * MyPerson Footer
     * 
     */
    private String footer;

    /**
     * Sets header field value.
     * 
     * @param header
     *                 The header to set.
     */
    public final void setHeader(String header) {
        this.header = header;
    }

    /**
     * This method returns the header value.<BR>
     * 
     * @return
     *     Returns the header.
     */
    @Fields({
        @Field(offset = 1, length = 5, paddingChar = '*')
    })
    public final String getHeader() {
        return this.header;
    }

    /**
     * Sets firstname field value.
     * 
     * @param firstname
     *                 The firstname to set.
     */
    public final void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    /**
     * This method returns the firstname value.<BR>
     * 
     * @return
     *     Returns the firstname.
     */
    @Fields({
        @Field(offset = 6, length = 10, paddingChar = ' ')
    })
    public final String getFirstname() {
        return this.firstname;
    }

    /**
     * Sets lastname field value.
     * 
     * @param lastname
     *                 The lastname to set.
     */
    public final void setLastname(String lastname) {
        this.lastname = lastname;
    }

    /**
     * This method returns the lastname value.<BR>
     * 
     * @return
     *     Returns the lastname.
     */
    @Fields({
        @Field(offset = 16, length = 10, paddingChar = ' ')
    })
    public final String getLastname() {
        return this.lastname;
    }

    /**
     * Sets age field value.
     * 
     * @param age
     *                 The age to set.
     */
    public final void setAge(int age) {
        this.age = age;
    }

    /**
     * This method returns the age value.<BR>
     * 
     * @return
     *     Returns the age.
     */
    @Fields({
        @Field(offset = 26, length = 2, paddingChar = ' ')
    })
    public final int getAge() {
        return this.age;
    }

    /**
     * Sets joiningDate field value.
     * 
     * @param joiningDate
     *                 The joiningDate to set.
     */
    public final void setJoiningDate(Date joiningDate) {
        this.joiningDate = joiningDate;
    }

    /**
     * This method returns the joiningDate value.<BR>
     * 
     * @return
     *     Returns the joiningDate.
     */
    @Fields({
        @Field(offset = 28, length = 9, paddingChar = ' ')
    })
    @FixedFormatPattern("ddMMMyyyy")
    public final Date getJoiningDate() {
        return this.joiningDate;
    }

    /**
     * Sets salary field value.
     * 
     * @param salary
     *                 The salary to set.
     */
    public final void setSalary(Double salary) {
        this.salary = salary;
    }

    /**
     * This method returns the salary value.<BR>
     * 
     * @return
     *     Returns the salary.
     */
    @Fields({
        @Field(offset = 37, length = 8, align = Align.RIGHT, paddingChar = ' ')
    })
    @FixedFormatDecimal(decimals = 3)
    public final Double getSalary() {
        return this.salary;
    }

    /**
     * Sets filler field value.
     * 
     * @param filler
     *                 The filler to set.
     */
    public final void setFiller(String filler) {
        this.filler = filler;
    }

    /**
     * This method returns the filler value.<BR>
     * 
     * @return
     *     Returns the filler.
     */
    @Fields({
        @Field(offset = 45, length = 22, paddingChar = ' ')
    })
    public final String getFiller() {
        return this.filler;
    }

    /**
     * Sets footer field value.
     * 
     * @param footer
     *                 The footer to set.
     */
    public final void setFooter(String footer) {
        this.footer = footer;
    }

    /**
     * This method returns the footer value.<BR>
     * 
     * @return
     *     Returns the footer.
     */
    @Fields({
        @Field(offset = 67, length = 5, paddingChar = '*')
    })
    public final String getFooter() {
        return this.footer;
    }

}
